# Generated by Django 4.1 on 2022-09-14 11:59

import chords.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scale',
            name='notes',
            field=models.JSONField(default=chords.models.c_major_scale, verbose_name='Notes'),
        ),
    ]
