# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        stages: [ commit ]
        args: [ '--check', '--config', 'pyproject.toml' ]
        types: [ python ]
      - id: black
        stages: [ manual ]
        args: [ '--config', 'pyproject.toml' ]
        types: [ python ]
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.0
    hooks:
      - id: flake8
        args: [ '--config', '.flake8' ]
        additional_dependencies: [ 'flake8-isort' ]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        stages: [ manual ]
        name: isort (python)
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.5.0
    hooks:
      - id: docformatter
        stages: [ commit ]
        args: [ '--check', '--config', 'pyproject.toml', '--pre-summary-newline' ]
      - id: docformatter
        stages: [ manual ]
        args: [ '--in-place', '--config', 'pyproject.toml', '--pre-summary-newline' ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
        entry: mypy .
        pass_filenames: false
        args: [ '--ignore-missing-imports' ]
        language_version: python3.10
        additional_dependencies:
          - types-python-dateutil
          - types-requests