---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: 3.12.1-alpine3.19
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: python -m pip install -r requirements.dev.txt -r requirements.txt
      - name: Test
        run: python -m pytest tests
